services:
  cakephp-app:
    container_name: cakephp-app
    build: .
    volumes:
      - ./cake-app:/var/www/html
    ports:
      - "${APP_PORT}:80"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      TEST_DATABASE_URL: "${TEST_DATABASE_URL}"

  db:
    image: mysql:5.7
    container_name: cakephp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  test_db:
    image: mysql:5.7
    container_name: cakephp-test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${TEST_MYSQL_DATABASE}"
    ports:
      - "${TEST_DB_PORT}:3306"
    volumes:
      - test_db_data:/var/lib/mysql

volumes:
  db_data:
  test_db_data:
